### ISSUE TITLE
Update Auth Page using form with field validation

### ISSUE THREAD

**Issue by mudoker** [zenbright/bright-frontend#40]
Show errors on invalid fields using Form components from React form, zod validator alongs with Shadcn form components

**Comment by ankiiisharma** [comment]
hey @Mudoker , i want to work on this issue, can you please assign this to me. thanks

**Comment by mudoker** [comment]
@ankiiisharma  Please fork the project and run pnpm install (we use pnpm for performance).

The task is straightforward: wrap components in Form components from Shadcn and React hooks, and validate fields using Zod. At the moment, just make sure all the fields are not empty on submit.

Ref: 
Shadcn form: https://ui.shadcn.com/docs/components/form
Code example: Navigate to src/features/project/task/task-creation-form.jsx

**Comment by mudoker** [comment]
Done
